name: Build Unichristus List LaTeX
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: main_artifact
          path: main.pdf
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Version
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.${{ github.run_number }}
          release_name: Automated Release v1.1.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: main_artifact


      - name: Upload Release Asset
        id: update-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: result_final.pdf
          asset_content_type: pdf 
