name: Release Unichristus List LaTeX
on:
  push:
    branches: [master]
jobs:
  release_latex:
    runs_on: ubuntu-latest
    steps:
      - name: Create Release Version
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.1
          release_name: Automated build v1.1.1
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: update-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main.pdf
          asset_name: result.pdf
          asset_content_type: application/pdf 